language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore ./Order.Contracts/Order.Contracts.sln
  - dotnet build ./Order.Contracts/Order.Contracts.sln
  - dotnet restore ./Payment.Contracts/Payment.Contracts.sln
  - dotnet build ./Payment.Contracts/Payment.Contracts.sln
  - dotnet restore ./Logging/Logging.sln
  - dotnet build ./Logging/Logging.sln